# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-26 20:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_date', models.DateField(max_length=50)),
                ('initial_amount', models.DecimalField(decimal_places=2, max_digits=19)),
                ('final_amount', models.DecimalField(decimal_places=2, max_digits=19)),
                ('account_type', models.CharField(max_length=50)),
                ('profile', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastname', models.CharField(max_length=50)),
                ('firstname', models.CharField(max_length=50)),
                ('sex', models.CharField(max_length=50)),
                ('birthdate', models.DateField()),
                ('status', models.CharField(max_length=50)),
                ('job', models.CharField(max_length=50)),
                ('company', models.CharField(max_length=50)),
                ('children', models.DecimalField(decimal_places=0, max_digits=2)),
                ('area', models.CharField(max_length=50)),
                ('profile', models.CharField(max_length=50)),
                ('start_date_relation', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='customer.Client'),
        ),
    ]
